// 최신 git 태그를 읽어 src/version.ts 를 자동 생성하는 스크립트
// 형식: "2026-03-03-1" → "2026-03-03 - 1"
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'src', 'version.ts');

try {
  const tag = execSync('git describe --tags --abbrev=0 2>&1').toString().trim();
  const formatted = tag.replace(/^(\d{4}-\d{2}-\d{2})-(\d+)$/, '$1 - $2');
  fs.writeFileSync(
    outPath,
    `// Auto-generated by scripts/version.js — do not edit manually\nexport const APP_VERSION = '${formatted}';\n`
  );
  console.log(`[version] ${formatted}`);
} catch {
  // 태그가 없으면 기존 파일 유지
  if (!fs.existsSync(outPath)) {
    fs.writeFileSync(outPath, `export const APP_VERSION = '—';\n`);
  }
  console.log('[version] No tag found, keeping existing version.ts');
}
